<?php

namespace App\Imports;

use App\Models\TimeoffPolicy;
use App\Models\TimeoffQuota;
use App\Models\User;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\Importable;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class ImportTimeoffQuotaImport implements ToCollection, WithHeadingRow
{
    use Importable;

    /**
     * @param Collection $collection
     */
    public function collection(Collection $collection)
    {
        foreach ($collection as $data) {
            $user = User::firstWhere('nik', $data['nik']);
            $timeoffPolicy = TimeoffPolicy::firstWhere('code', $data['timeoff_policy_code']);

            if ($user && $timeoffPolicy) {
                $timeoffQuota = TimeoffQuota::create([
                    'timeoff_policy_id' => $timeoffPolicy->id,
                    'user_id' => $user->id,
                    'effective_start_date' => '2024-01-01',
                    'quota' => $data['balance'],
                ]);

                $timeoffQuota->timeoffQuotaHistories()->create([
                    'user_id' => $user->id,
                    'is_increment' => true,
                    'new_balance' => $timeoffQuota->quota,
                    'description' => 'Generated by system'
                ]);
            }
        }
    }
}
